
<div class="row headline">
    <div class="span4">
        <img class='full-border-thick' src='<?php echo $this->vehicle['photo'] ?>'/>
        <p></p>
        <p>   
            <a class='btn btn-primary btn-block' target='_blank' href='<?php echo $this->url(array('controller' => 'vehicle' ,'action'=>'servepdf', 'uvc'=> $this->vehicle['full_uvc']), null, true);?>'>Download New Car Cost Guide</a>
        </p>
    </div>
    <div class="span7 well">
        <div class="row">
            <div class="span8">
                <h1><?php echo $this->vehicle['display_title'] ?></h1>
            </div>
        </div>
        <div class="row">
            <div class="span3">
                <strong>Wholesale Value:</strong> $<?php echo number_format($this->vehicle['base_whole_avg'], 2) ?>
            </div>
            <div class="span3">
                <strong>Body Style:</strong> <?php echo $this->vehicle['body_style'] ?>
            </div>
        </div>
        <div class="row">
            <div class="span3">
                <strong>Trade In Value:</strong> $<?php echo number_format($this->vehicle['tradein_avg'], 2) ?>
            </div>
            <div class="span3">
                <strong>Engine:</strong> <?php echo $this->vehicle['engine_description'] ?>
            </div>
        </div>
        <div class="row">
            <div class="span3">
                <strong>Market Value:</strong> $<?php echo number_format($this->vehicle['retail_avg'], 2) ?>
            </div>
            <div class="span3">
                <strong>Transmission:</strong> <?php echo $this->vehicle['transmission'] ?>
            </div>
        </div>
        <div class="row">
            <div class="span3">
                <strong>New MSRP:</strong> $<?php echo number_format($this->vehicle['msrp'], 2) ?>
            </div>
            <div class="span3">
                <strong>Miles Per Gallon (City):</strong> 
                <?php if($this->vehicle['city_mpg'] == '') { ?>
                    N/A
                <?php } else { ?>
                    <?php echo number_format($this->vehicle['city_mpg'], 1) ?>
                <?php } ?>
            </div>
        </div>
        <div class="row">
            <div class='span3'>  
                <strong>Exterior Colors: </strong>
                <ul class='gallery-post-grid swatches'>
                    <?php if(!is_array($this->vehicle['external_colors'])) { ?>
                        N/A
                    <?php } else { ?>
                        <?php foreach( $this->vehicle['external_colors'] as $color ) { ?>
                        <li><div class='swatch' style="background: <?php echo $color['swatch'] ?>"></div></li>
                        <?php } ?>
                    <?php } ?>
                </ul>
            </div>
            <div class='span3'>  
                <strong>Interior Colors: </strong>
                <ul class='gallery-post-grid swatches'>
                    <?php if(!is_array($this->vehicle['interior_colors'])) { ?>
                        N/A
                    <?php } else { ?>
                        <?php foreach( $this->vehicle['interior_colors'] as $color ) { ?>
                        <li><div class='swatch' style="background: <?php echo $color['swatch'] ?>"></div></li>
                        <?php } ?>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <div class='row'>
            <div class='span7'>
                <a href='#details' class='btn btn-primary btn-block'>View More Specifications</a>
            </div>
        </div>
    </div>
</div>

<div class="articles">
    <h2 class='text-center'><?php echo $this->vehicle['make'] ?> Articles</h2>
    <div class='row clearfix no-margin'>
        <ul class='gallery-post-grid holder'>
            <?php $articleCount = 0; foreach($this->vehicle['articles'] as $article) { ?>
                <?php if($articleCount++ == 3) break; ?>
                <li class='span4 gallery-item'>
                    <a href="#"><img src="<?php echo $article['image']; ?>" alt="Gallery"></a>
                    <span class="project-details"><a href="#"><?php echo $article['fullTitle']; ?></a><?php echo $article['fullDek'] ?></span>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>

<div class='detail'>
    <h2 class='text-center'>Details</h2>
    <div id='details' class='row clearfix no-margin'>
        <ul class='nav nav-tabs'>
            <li class='active'><a href='#sche' data-toggle='tab'>Maintenance Schedule</a></li>
            <li><a href='#financing' data-toggle='tab'>New Car Financing</a></li>
            <li><a href='#performance' data-toggle='tab'>Performance Data</a></li>
        </ul>
        <div class='tab-content'>
            <div class='tab-pane active' id='sche'>
                <?php if($this->maintenanceData) { ?>
                <h2>Parts you Need to Maintain Intervally</h2>
                <table class='table'>
                    <thead>
                        <tr>
                            <th>What</th>
                            <th>When</th>
                            <th>Estimated Mechanic Effort</th>
                            <th>Cost</th>
                            <th>Reminder</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->maintenanceData['distance'] as $item) { ?>
                        <tr>
                            <td><?php echo $item['description'] ?></td>
                            <td><?php echo $item['frequency'] ?></td>
                            <td><?php echo $item['effort'] ?></td>
                            <td>$<?php echo number_format($item['effort'] * (100/60), 2) ?></td>
                            <td><a class='setup' href='#'>Setup Reminder</a></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                
                <h2>Parts you Need to Maintain on Indicator Light</h2>
                <table class='table'>
                    <thead>
                        <tr>
                            <th>What</th>
                            <th>When</th>
                            <th>Estimated Mechanic Effort</th>
                            <th>Cost</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->maintenanceData['indicator'] as $item) { ?>
                        <tr>
                            <td><?php echo $item['description'] ?></td>
                            <td><?php echo $item['frequency'] ?></td>
                            <td><?php echo $item['effort'] ?></td>
                            <td>$<?php echo number_format($item['effort'] * (100/60), 2) ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                
                <h2>Parts you Need to Maintain</h2>
                <table class='table'>
                    <thead>
                        <tr>
                            <th>What</th>
                            <th>When</th>
                            <th>Estimated Mechanic Effort</th>
                            <th>Cost</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->maintenanceData['other'] as $item) { ?>
                        <tr>
                            <td><?php echo $item['description'] ?></td>
                            <td>Unknown</td>
                            <td><?php echo $item['effort'] ?></td>
                            <td>$<?php echo number_format($item['effort'] * (100/60), 2) ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                <?php } else { ?>
                    <h2>Oh no! No data available.</h2>
                <?php } ?>
            </div>
            <div class='tab-pane' id='financing'>
                <div class='row'>
                    <div class='span5'>
                    <form id='financing-form' class='form-horizontal' action='<?php echo $this->url(array('controller'=>'finance', 'action'=>'index'), null, true) ?>'>
                        <input type='hidden' name='model' value='<?php echo $this->model ?>'/>
                        <div class='control-group'>
                            <label class='control-label' for='zipcode'>Zipcode*:</label>
                            <div class='controls'>
                                <input type='text' name='zipcode' placeholder='Zipcode'/>
                            </div>
                        </div>
                        <div class='control-group'>
                            <label class='control-label' for='lease'>Lease / Loan*:</label>
                            <div class='controls'>
                                <select name='lease'>
                                    <option value='lease'>Lease</option>
                                    <option value='loan'>Loan</option>
                                </select>
                            </div>
                        </div>
                        <div class='control-group'>
                            <label class='control-label' for='months'>Months*:</label>
                            <div class='controls'>
                                <select name='months'>
                                    <option value='24'>24</option>
                                    <option value='36'>36</option>
                                    <option value='48'>48</option>
                                    <option selected value='60'>60</option>
                                    <option value='72'>72</option>
                                </select>
                            </div>
                        </div>
                        <div class='control-group'>
                            <label class='control-label' for='downpay'>Down Payment*:</label>
                            <div class='controls'>
                                <input type='number' name='downpay' placeholder='0'/>
                            </div>
                        </div>
                        <div class='control-group'>
                            <label class='control-label' for='credit'>Credit Score*:</label>
                            <div class='controls'>
                                <input type='number' name='credit' placeholder='800'/>
                            </div>
                        </div>
                        <div class='control-group'>
                            <div class='controls'>
                                <button type="submit" class="btn btn-primary">Get Finance Data!</button>
                            </div>
                        </div>
                    </form>
                    </div>
                    <div class='clearfix span5 offset1 well' id='finance-target'>
                        Fill out the form for financing information. This may only be available in certain
                        zipcodes at this time.
                    </div>
                </div>
            </div>
            <div class='tab-pane' id='performance'>
                <h2>Real World Performance Metrics</h2>
                <?php if(!is_array($this->perfdata) || count($this->perfdata) == 0) { ?>
                    Sorry, there are no real world performance metrics for this car.
                <?php } else { ?>
                    <?php foreach($this->perfdata as $data) { ?>
                        <div class='row'>
                            <div class='span10 offset1 well'>
                                <h4>Performance Trial:</h4>
                                <table class='table'>
                                    <thead>
                                        <tr>
                                            <th>Metric</th>
                                            <th>Measurement</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach($data as $k=>$v) { ?>
                                        <?php 
                                            $k = str_replace("_", " ", $k);
                                            $k = ucwords($k);
                                            if(strpos($k, "Id")) continue;
                                            if(!$v || $v == '') continue;
                                        ?>
                                        <tr>
                                            <td><?php echo $k ?></td>
                                            <td><?php echo $v ?></td>
                                        </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    <?php } ?>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

<script type='text/javascript'>
(function($) {
	    $('#financing-form').submit(function(e) { 
	        e.preventDefault();

	        var data = $(this).serialize();
	        var url = $(this).attr('action');

	        $.post(url, data).success(function(data) {
		        data = JSON.parse(data);

		        var div = "";
		        var target = $("#finance-target");
		        if(data.length > 0)
		        {
			        target.empty();
			       /* $("#financing-form").parent().hide();
			        target.removeClass("span5").addClass("span10");*/
		        }
		        else
		        { 
			        target.html("No financing is available for these options at this time. Sorry, try again!");
		        }
	            for(var i = 0; i < data.length; i++)
	            {
		            var obj = data[i];
		            var title = obj.VehicleCode.Condition + " " + obj.VehicleDescription.Year + " " +  obj.VehicleDescription.Make +
		                " " + obj.VehicleDescription.Model + " " + obj.VehicleDescription.Style;
		            div += "<div class='row finance-entry hidden'>";
		            div += "<div class='span5'>";
			        div += "<h4>"+title+"</h4>";

			        var pager = "";
			        pager += '<div class="pagination">';
	                pager += '<ul>';
	                pager += '<li class="active"><a class="prev" href="#">Prev</a></li>';
	                pager += '<li><a class="next" href="#">Next</a></li>';
	                pager += '</ul>';
	                pager += '</div>';
	                div += pager;
	                
			        var table = "<table class='table'>";
			        table += "<thead><tr><th>APR</th><th>Monthly Payment</th><th>Term(M)</th><th>Down Payment</th><th>Residual Value</th></tr></thead><tbody>";
			        for(var j = 0; j < obj.payments.length; j++)
			        {
				        var payment = obj.payments[j];
				        table += "<tr>";
  			                table += "<td>" + payment.APRRounded + "</td>";
				            table += "<td>$" + payment.MonthlyPayment + "</td>";
				            table += "<td>" + payment.Term + "</td>";
				            table += "<td>$" + payment.DueAtSigning + "</td>";
				            table += "<td>$" + payment.ResidualDollar + "</td>";
				        table += "</tr>";
			        }
			        table += "</tbody></table>";
			        div += table;
		            div += "</div></div>";
		            target.append(div);
		            target.find(".finance-entry").first().removeClass('hidden');
		            checkPagination();
	            }
	        });
	        return false;
	    });
	    $("body").on('click', ".pagination a.next", function(e) {
		    var target = $(".finance-entry").not(".hidden");
		    if(target.next().length > 0)
		    	  target.toggleClass('hidden').next().toggleClass('hidden');
		    checkPagination();
	        e.preventDefault();
	        return false;
	    });
	    $("body").on('click', ".pagination a.prev", function(e) {
		    var target = $(".finance-entry").not(".hidden");
		    if(target.prev().length > 0)
		    	  $(".finance-entry").not(".hidden").toggleClass('hidden').prev().toggleClass('hidden');
	    	checkPagination();
	        e.preventDefault();
	        return false;
	    });

	    function checkPagination()
	    {
	    	if($(".finance-entry").not(".hidden").prev().length == 0)
		    	$(".pagination a.prev").parent().addClass("active");
	    	else
	    		$(".pagination a.prev").parent().removeClass("active");
    		
	    	if($(".finance-entry").not(".hidden").next().length == 0)
		    	$(".pagination a.next").parent().addClass("active");
		    else
		    	$(".pagination a.next").parent().removeClass("active");
	    }
	    window.checkPagination = checkPagination;

	    $(".setup").click(function(e) {
		    $("tr.temp").remove();
		    var row = "<tr class='temp'>";
		    row += "<td><input name='months-since' type='text' placeholder='Months Since Last' /></td>";
		    row += "<td><input name='miles-since' type='text' placeholder='Miles Since Last' /></td>";
		    row += "<td><input name='miles-per' type='text' placeholder='Miles Per Week' /></td>";
		    row += "<td><input name='email' type='text' placeholder='Email' /></td>";
		    row += "</tr>";
		    $(this).parents("tr").first().after(row);
	        e.preventDefault();
	        return true;
	    });
})(jQuery);
</script>