<div class="row headline">
	<!-- Begin Headline -->

	<!-- Slider Carousel
    ================================================== -->
	<div class="span8">
		<img src='/images/banner.jpg' />
	</div>
	<!-- Headline Text 
    ================================================== -->
	<div class="span4">
		<h3>
			Let us take care of your car information needs
		</h3>
		<a href='<?php echo $this->url(array('controller'=>'search', 'action'=>'index'), null, true) ?>' class='btn btn-primary btn-block'>Search for your vehicle today!</a>
	</div>
</div>
</div>
