<div class="row headline">
    <div class="span4">
        <img class='full-border-thick' src='<?php echo $this->vehicle['photo'] ?>'/>
        <p></p>
        <p>   
            <a class='btn btn-primary btn-block'>Change Year</a>
        </p>
        <p>   
            <a class='btn btn-primary btn-block' target='_blank' href='<?php echo $this->url(array('action'=>'servepdf', 'uvc'=> $this->vehicle['full_uvc']), null, true);?>'>Download New Car Cost Guide</a>
        </p>
    </div>
    <div class="span7 well">
        <div class="row">
            <div class="span8">
                <h1><?php echo $this->vehicle['display_title'] ?></h1>
            </div>
        </div>
        <div class="row">
            <div class="span3">
                <strong>Wholesale Value:</strong> $<?php echo number_format($this->vehicle['base_whole_avg'], 2) ?>
            </div>
            <div class="span3">
                <strong>Body Style:</strong> <?php echo $this->vehicle['body_style'] ?>
            </div>
        </div>
        <div class="row">
            <div class="span3">
                <strong>Trade In Value:</strong> $<?php echo number_format($this->vehicle['tradein_avg'], 2) ?>
            </div>
            <div class="span3">
                <strong>Engine:</strong> <?php echo $this->vehicle['engine_description'] ?>
            </div>
        </div>
        <div class="row">
            <div class="span3">
                <strong>Market Value:</strong> $<?php echo number_format($this->vehicle['retail_avg'], 2) ?>
            </div>
            <div class="span3">
                <strong>Transmission:</strong> <?php echo $this->vehicle['transmission'] ?>
            </div>
        </div>
        <div class="row">
            <div class="span3">
                <strong>New MSRP:</strong> $<?php echo number_format($this->vehicle['msrp'], 2) ?>
            </div>
            <div class="span3">
                <strong>Miles Per Gallon (City):</strong> <?php echo number_format($this->vehicle['city_mpg'], 1) ?>
            </div>
        </div>
        <div class="row">
            <div class='span3'>  
                <strong>Exterior Colors: </strong>
                <ul class='gallery-post-grid swatches'>
                    <?php foreach( $this->vehicle['external_colors'] as $color ) { ?>
                    <li><div class='swatch' style="background: <?php echo $color['swatch'] ?>"></div></li>
                    <?php } ?>
                </ul>
            </div>
            <div class='span3'>  
                <strong>Interior Colors: </strong>
                <ul class='gallery-post-grid swatches'>
                    <?php foreach( $this->vehicle['interior_colors'] as $color ) { ?>
                    <li><div class='swatch' style="background: <?php echo $color['swatch'] ?>"></div></li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <div class='row'>
            <div class='span7'>
                <a href='#' class='btn btn-primary btn-block'>View More Specifications</a>
            </div>
        </div>
    </div>
</div>

<div class="articles">
    <h2 class='text-center'><?php echo $this->vehicle['make'] ?> Articles</h2>
    <div class='row clearfix no-margin'>
        <ul class='gallery-post-grid holder'>
            <?php $articleCount = 0; foreach($this->vehicle['articles'] as $article) { ?>
                <?php if($articleCount++ == 3) break; ?>
                <li class='span4 gallery-item'>
                    <a href="#"><img src="<?php echo $article['image']; ?>" alt="Gallery"></a>
                    <span class="project-details"><a href="#"><?php echo $article['fullTitle']; ?></a><?php echo $article['fullDek'] ?></span>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>