<!doctype HTML>
<html>
<head>
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <!-- 
    <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    -->
    <link href="/theme/style.css" rel="stylesheet" media="screen">
</head>
<body>
    <div class="color-bar-1"></div>
    <div class="color-bar-2 color-bg"></div>
    <div class="container">
        <div class="row header">
            <div class="span5 logo">
                <a href="/"><img src='http://placehold.it/290x50'/></a>
            </div>    
            <div class="span7 navigation">
                <div class="navbar <!--hidden-phone-->">
                    <ul class="nav">
                        <li class="active"><a href='#'>Home</a></li>
                        <li><a href='#'>Car Search</a></li>
                    </ul>
                </div>
            </div>
        </div>       
        
        <?php echo $this->layout()->content; ?>
    </div>
    
    <script src="/bootstrap/js/jquery.min.js" type="text/javascript"></script>
    <script src="/bootstrap/js/bootstrap.js" type="text/javascript"></script>

</body>
</html>