<!doctype HTML>
<html>
<head>
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <!-- 
    <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    -->
    <link href="/theme/style.css" rel="stylesheet" media="screen">
    
    <script src="/bootstrap/js/jquery.min.js" type="text/javascript"></script>
    <script src="/bootstrap/js/bootstrap.js" type="text/javascript"></script>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
    <style>
    h1,h2,h3,h4,h5,h6 { font-family: 'Roboto Slab', serif; text-shadow: 1px 1px 2px rgba(150, 150, 150, 1); }
    </style>
</head>
<body>
    <div class="color-bar-1"></div>
    <div class="color-bar-2 color-bg"></div>
    <div class="container">
        <div class="row header">
            <div class="span5 logo">
                <a href="/"><img src='/images/logo.png'/></a>
            </div>    
            <div class="span7 navigation">
                <div class="navbar <!--hidden-phone-->">
                    <ul class="nav">
                        <li class="active"><a href='/'>Home</a></li>
                        <li><a href='<?php echo $this->url(array('controller'=>'search', 'action'=>'index'), null, true) ?>'>Car Search</a></li>
                    </ul>
                </div>
            </div>
        </div>       
        
        <?php echo $this->layout()->content; ?>
    </div>
    <div class='row'></div>
    <div class="footer-container"><!-- Begin Footer -->
    	<div class="container">
        	<div class="row footer-row">
        	    <span class='pull-left footer-col'>Copyright 2013 &clubs; MHacks Dream Team</span>
        	    <span class='pull-right footer-col'>APIs used &clubs; Hearst Automotive &clubs; Bing Image &clubs; MongoDB &clubs; Sendgrid &clubs; Car and Driver</span>
            </div>
        </div>
    </div>
</body>
</html>